version: '3'

networks:
  web:
    external: true

volumes:
  mysql:
    driver: local

services:
  app:
    labels:
      - "traefik.enable=false"

  nginx:
    networks:
      - web
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.wall-http.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.wall-http.entrypoints=http"
      - "traefik.http.routers.wall-http.middlewares=https-redirect@docker"

      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

      - "traefik.http.routers.wall-https.entrypoints=https"
      - "traefik.http.routers.wall-https.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.wall-https.tls=true"
      - "traefik.http.routers.wall-https.tls.certresolver=letsencrypt"

  mysql:
    volumes:
      - 'mysql:/var/lib/mysql'

    labels:
      - "traefik.enable=false"
